### ISSUE TITLE
Unable to log into front-end on staging

### ISSUE THREAD

**Issue by natalieblackburn** [mozilla/m-response#257]
You can't currently log in to the front-end view on staging as a normal user, only via the admin first. To be able to test the permissions, we need to be able to log in as end users to the front-end of the application on staging

Current behaviour: go to https://mozilla-respond-qa.herokuapp.com/ and select to log in, see a blank screen and this URL: https://mozilla-respond-qa.herokuapp.com/oidc/authenticate/None/?response_type=code&scope=openid+email&client_id=None&redirect_uri=https%3A%2F%2Fmozilla-respond-qa.herokuapp.com%2Foidc%2Fcallback%2F&state=sublPA7vU7C3Ywlk3i942BzVWbTo21g5&nonce=v9nZBlOXcJjJrxzbYYt4p3AkdsrAQNGI

**Comment by natalieblackburn** [comment]
Create a basic django login / reconfigure what's existing to find the quickest solution to being able to log in as a user to the front-end of the app without a staff account, to enable testing. Timebox to 1hr

**Comment by tm-kn** [comment]
This is on the dev server - https://mozilla-respond-qa.herokuapp.com/oidc/authenticate/

**Comment by natalieblackburn** [comment]
Tomasz is looking into this further, it seems to check the credentials OK and I can log in using correct details for a test user, but accessing /dashboard is showing a blank screen, so looks like there is a front-end bug stopping the usual page displaying

**Comment by tm-kn** [comment]
@natalieblackburn Try now. I think I've fixed the front-end issue.

**Comment by natalieblackburn** [comment]
Interestingly it works fine logging in on my own account (as an admin user), I can get in through this new link and see the dashboard. When I try logging in as tbx-test with correct credentials though, I still see a blank screen at /dashboard.

I also tried creating a new non-admin user to test with instead of that one, and got a 500 server error

**Comment by tm-kn** [comment]
I've tested it with a couple of new users. You may have to try incognito mode or force refreshing. Maybe you still have old JS in the cache.

**Comment by natalieblackburn** [comment]
I've been able to test this now, so I've created tbx-test-2 and tbx-test-3 who are in the level 1 and level 2 groups respectively. The workflow for their responses is working as expected, with level 1 still requiring staff moderation, and level 2 only needing submitting to the play store.

This is ready for your testing Madalina, let me know if it's clear enough for you test

**Comment by madasan** [comment]
This seems to work fine

**Comment by madasan** [comment]
This seems to have stopped working again. Any new users I'm creating get a blank screen when trying to log in. Works fine for users with admin status.

**Comment by madasan** [comment]
Ok I might have solved it, it looks like a language input field issue.

**Comment by natalieblackburn** [comment]
Thanks Madalina, closing issue.

**Comment by natalieblackburn** [comment]
In fact will reopen and close it when it's deployed but moving it to Done
